%lang starknet

const MAP_WIDTH = 20727
const MAP_HEIGHT = 11900
const MAP_INNER_AREA_WIDTH = 5000
const MAP_INNER_AREA_HEIGHT = 5000
const CHEST_PER_PLAYER = 3
const ORE_PER_PLAYER = 3
const MAX_PLAYERS = 2
const PREPARE_TIME = 300 # how much time for preparation time
const FIRST_STAGE_DURATION = 600
const SECOND_STAGE_DURATION = 600

const KOMA_MOVING_SPEED = 20
const KOMA_ATK = 7
const KOMA_DEFENSE = 15
const WORKER_MINING_SPEED = 200

const BOT_TYPE_WORKER = 1
const BOT_TYPE_DRONE = 2